-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.candidate_verification_code
(
    user_id integer NOT NULL,
    candidate_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.candidates
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    identity_number character(11) NOT NULL,
    birthdate date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employer_verification_by_personnel
(
    user_id integer NOT NULL,
    employer_id integer NOT NULL,
    identity_of_verifiying_personnel integer NOT NULL,
    is_verified boolean NOT NULL,
    verification_date date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employer_verification_code
(
    user_id integer NOT NULL,
    employer_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    website_adress character varying(50) NOT NULL,
    phone_number character varying(20) NOT NULL,
    is_verified boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.personnel
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.titles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_title character varying(60) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(40) NOT NULL,
    password character varying(20) NOT NULL,
    dtype character varying(31) NOT NULL,
    birthdate date,
    first_name character varying(255),
    identity_number character varying(255),
    last_name character varying(255),
    company_name character varying(255),
    is_verified boolean,
    phone_number character varying(255),
    website_adress character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.verificationcode
(
    id integer NOT NULL,
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    verification_code character varying(15) NOT NULL,
    is_verified boolean NOT NULL,
    verification_date date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.candidate_verification_code
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (user_id)
    NOT VALID;


ALTER TABLE public.candidates
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employer_verification_by_personnel
    ADD FOREIGN KEY (identity_of_verifiying_personnel)
    REFERENCES public.personnel (user_id)
    NOT VALID;


ALTER TABLE public.employer_verification_by_personnel
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.employer_verification_code
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.employer_verification_code
    ADD FOREIGN KEY (user_id)
    REFERENCES public.employer_verification_code (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.personnel
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;